def display_menu():
    print("\n==============================")
    print("🤖 Agentic AI CLI")
    print("==============================")
    print("1. Explain AI Concept")
    print("2. Summarize Text")
    print("3. Generate Interview Question")
    print("4. Generate Python code")
    print("5. Exit")
    print("Try differently !!!")
